# -*- coding: utf-8 -*-
"""ODEtester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FwzbRpxb9zaV8t2D4dqQnZvYZZ-ZVz4Y

ODE one
"""

#PHY607 Project 1 ODE portion

#imports are numpy, matplotlib, sympy

import numpy as np
import matplotlib.pyplot as plt
from sympy import Symbol

#2.0 The differential equation half---

#2.1 Choose ODE method solver
E=0.0301; RK4=0.0302;
B = eval(input("Please input which integration method - E, RK4: "))

#2.2 The differential equation of choice is-
#u*d^2/dt^2 r(t) = L^2/(u*r(t)^3)-G*M*u/r(t)^2

#2.21 ICs : Let r(0)=r0, d/dt r(t)|t=0 = v0, the update equations:
r0, v0 = map(eval,input("Input initial position, velocity: ").split(","))

#2.22 Precision of diff. eq (steps)
Nd, dt = map(float,input("Input desired step quantity, and step size: ").split(","));Nd=int(Nd)
timee=np.empty(Nd+1); timee[0]=0
r=np.empty(Nd+1);r[0]=r0
rdot=np.empty(Nd+1);rdot[0]=v0
rana=np.empty(Nd+1);rana[0]=r0
energy=np.empty(Nd+1)
#L=Symbol('L'); u=Symbol('u');
#G=Symbol('G'); M=Symbol('M')
#^having float based issues... don't have more time/not sure how to fix
#input parameters
G, M, m, thetadot = map(eval,input("Input Newton's constant, large object mass M, small object m, thetadot: ").split(","))
u=M*m/(M+m); L=u*r0**2*thetadot
theta = np.empty(Nd+1); theta[0] = 0

#2.23 necessary turning point analysis as described under Figure 3.14 page 96 Goldstein
ecc=(1 + 2*energy[0]*L**2/(G**2*M**2*u**3))**0.5

if abs(v0) <= 1e-8:
    thetap = np.pi if r0 >(L**2/(G*M*u**2)) else 0 #use eq 3.63 to get this condition-since theta0=0, either r is smaller or larger than the denominator-and the denominator reduces to this form
else:
  thetap=np.arccos(np.clip(((L**2/(G*M*u**2))/r0 - 1) / ecc,-1,1))


#2.24 set more initial conditions (cause forgot before)

energy[0]=0.5*u*rdot[0]**2 + 0.5*(L**2)/(u*r[0]**2) - G*M*u/r[0]

#2.3 Euler Solver - note rana is the r(t) analytic, r plain is the RK4 one - though rana uses theta RK4 solved, r uses RK4 twice, and as described, r has no true analytic solution regardless since theta(t) is transcendental
if B==E:
  for i in range(Nd):
    timee[i+1]=timee[i]+dt
    rdot[i+1]=float(rdot[i]+dt*(L**2/(u**2*r[i]**3)-G*M/r[i]**2))
    r[i+1]=float(r[i]+dt*rdot[i+1])
    energy[i+1] = 0.5*u*rdot[i+1]**2 + 0.5*(L**2)/(u*r[i+1]**2) - G*M*u/r[i+1]
    theta[i+1] = theta[i] + dt * (L / (u * r[i]**2))
    rana[i+1] = (L**2/(G*M*u**2)) / (1 + (1 + 2*energy[0]*L**2/(G**2*M**2*u**3))**0.5 * np.cos(theta[i+1] - thetap))
    if i % 100 == 0:
      print("r, rdot (aka V) at time t=",timee[i],":",r[i],rdot[i])
    if r[i]<=0:
      print("hit physical barrier-input parameters predict collision in finite time")
#2.4 RK4 Solver
if B==RK4:
  def accel(r):
    return (L**2/(u**2*r**3)-G*M/r**2)
  for i in range(Nd):
    #2.41 thinking about below was an exercise (for the better or worse)
    a1=dt*rdot[i]
    b1=dt*accel(r[i])
    a2=dt*(rdot[i]+b1/2)
    b2=dt*accel(r[i]+a1/2)
    a3=dt*(rdot[i]+b2/2)
    b3=dt*accel(r[i]+a2/2)
    a4=dt*(rdot[i]+b3)
    b4=dt*accel(r[i]+a3)
    #2.42 using a, b,c  to update, oh and split d^2/dt^2 r = d/dt v
    timee[i+1]=timee[i]+dt
    r[i+1]=r[i]+(1/6)*(a1+2*a2+2*a3+a4)
    rdot[i+1]=rdot[i]+(1/6)*(b1+2*b2+2*b3+b4)
    c1 = dt * (L / (u * r[i]**2))
    c2 = dt * (L / (u * (r[i] + a1/2)**2))
    c3 = dt * (L / (u * (r[i] + a2/2)**2))
    c4 = dt * (L / (u * (r[i] + a3)**2))
    theta[i+1] = theta[i] + (1/6)*(c1 + 2*c2 + 2*c3 + c4)
    energy[i+1] = 0.5*u*rdot[i+1]**2 + 0.5*(L**2)/(u*r[i+1]**2) - G*M*u/r[i+1]
    rana[i+1] = (L**2/(G*M*u**2)) / (1 + (1 + 2*energy[0]*L**2/(G**2*M**2*u**3))**0.5 * np.cos(theta[i+1] - thetap))
    if i % 100 == 0:
      print("r, rdot (aka V) at time t=",timee[i],":",r[i],rdot[i])
    if r[i]<=0:
      print("hit physical barrier-input parameters predict collision in finite time")

#2.5 The plots - their titles explain them

plt.figure(1)
plt.title(f"radius vs theta mod 2pi, theta0=0, r0={r0},v0={v0} - it will connect θ=2pi, θ=0...")
plt.plot((theta % (2*np.pi)), r)
plt.axis('equal') #https://stackoverflow.com/questions/17990845/how-do-i-equalize-the-scales-of-the-x-axis-and-y-axis
plt.show()

plt.figure(2)
plt.title(f"Orbit plot position (x,y) versus time, theta0=0, r0={r0},v0={v0}")
plt.plot(r*np.sin(theta),r*np.cos(theta))
plt.axis('equal')
plt.show()

plt.figure(3)
plt.title("Actual analytic r(theta) formula")
plt.plot(rana*np.sin(theta),rana*np.cos(theta))
plt.axis('equal')
plt.show()

plt.figure(4)
plt.title("Difference in analytic r(t), and numerical")
plt.plot((rana-r)*np.sin(theta),(rana-r)*np.cos(theta))
plt.axis('equal')
plt.show()

plt.figure(5)
plt.title("Energy plot")
plt.plot(timee,energy)
plt.axis([0,Nd*dt,min(energy)/1.01,max(energy)*1.01])
plt.show()

#2.6 Optional useful diagnostic for user - see energy drift
for i in range(len(energy)):
  if i % int(Nd/100) == 0:
      print("E: ", energy[i])
      #print("theta: ", theta[i])

#Further Future Analysis